import { NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { deploymentRepositoryReference, validateEnvironmentInput } from "@/lib/deployments/config";
import { assertPortScopeAvailable, validateEnvironmentTarget } from "@/lib/deployments/target";
import { deploymentError, deploymentIdentity, forbidden, invalid, notAuthenticated } from "@/lib/deployments/api";
export const runtime = "nodejs"; export const dynamic = "force-dynamic";
async function owned(id: string) { const identity = await deploymentIdentity(); if (!identity) return { response: notAuthenticated() }; const project = await prisma.project.findFirst({ where: { id, userId: identity.userId } }); if (!project) return { response: forbidden() }; return { identity, project }; }
export async function GET(request: Request, context: { params: Promise<{ id: string }> }) { try { const { id } = await context.params; const access = await owned(id); if (access.response) return access.response; const items = await prisma.deploymentEnvironment.findMany({ where: { projectId: id }, orderBy: { createdAt: "asc" }, include: { server: { select: { id: true, name: true, status: true, dockerAvailable: true, dockerVersion: true, hostname: true, port: true } } } }); return NextResponse.json(items); } catch (error) { return deploymentError(error); } }
export async function POST(request: Request, context: { params: Promise<{ id: string }> }) { try { const { id } = await context.params; const access = await owned(id); if (access.response) return access.response; const body = await request.json().catch(() => null) as Record<string, unknown> | null; if (!body) return invalid("Request body must be valid JSON."); let config; try { config = validateEnvironmentInput(body); } catch (error) { return invalid(error instanceof Error ? error.message : "Environment configuration is invalid."); }
    // The target is resolved against the authenticated user's servers before anything is written, so a
    // remote environment can only ever point at a Server this user owns and can actually deploy to.
    let target; try { target = await validateEnvironmentTarget(access.identity.userId, body); } catch (error) { return invalid(error instanceof Error ? error.message : "Deployment target is invalid."); }
    const repositoryPath = body.repositoryPath === undefined ? access.project.localRepositoryPath : body.repositoryPath; let validatedRepositoryPath: string; try { validatedRepositoryPath = (await deploymentRepositoryReference(repositoryPath)).repositoryPath; } catch (error) { return deploymentError(error); }
    const existing = await prisma.deploymentEnvironment.findFirst({ where: { projectId: id, slug: config.slug } }); if (existing) return NextResponse.json({ code: "duplicate_environment", message: "Environment already exists." }, { status: 409 });
    // Host ports only collide on the same Docker host, so the scope is part of the uniqueness check.
    if (await assertPortScopeAvailable(target.portScopeKey, config.hostPort)) return NextResponse.json({ code: "port_in_use", message: "Host port is already assigned to another environment on this target." }, { status: 409 });
    await prisma.project.update({ where: { id }, data: { localRepositoryPath: validatedRepositoryPath } }); const environment = await prisma.deploymentEnvironment.create({ data: { projectId: id, ...config, target: target.target, serverId: target.serverId, portScopeKey: target.portScopeKey } }); return NextResponse.json(environment, { status: 201 }); } catch (error) { return deploymentError(error); } }
