import { getGitStatus } from "./status.ts";
import { runGit, GitError } from "./runner.ts";
import { validateBranchName, validateRepositoryPath, GitValidationError } from "./validation.ts";
import type { GitCommit } from "./types.ts";

function ensureClean(status: Awaited<ReturnType<typeof getGitStatus>>, message = "The working tree has uncommitted changes.") { if (status.detached) throw new GitError("detached_head", "The repository is in detached HEAD state.", 409); if (status.conflictedFiles.length) throw new GitError("conflict", "The repository has unresolved conflicts.", 409); if (!status.clean) throw new GitError("dirty_worktree", message, 409); }
async function commitDetails(repositoryRoot: string): Promise<GitCommit> { const result = await runGit(["log", "-1", "--format=%H%x00%h%x00%s%x00%an%x00%cI%x00%P"], repositoryRoot); const [hash, shortHash, subject, author, timestamp, parents = ""] = result.stdout.trim().split("\0"); return { hash, shortHash, subject, author, timestamp, parents: parents.split(" ").filter(Boolean) }; }
export async function createBranch(repositoryRoot: string, name: string) { validateBranchName(name); try { await runGit(["check-ref-format", "--branch", name], repositoryRoot); } catch { throw new GitValidationError("invalid_branch", "Branch name is invalid."); } await runGit(["branch", name], repositoryRoot); return name; }
export async function checkoutBranch(repositoryRoot: string, name: string) { validateBranchName(name); const status = await getGitStatus(repositoryRoot); ensureClean(status, "Checkout requires a clean working tree so local changes cannot be overwritten."); await runGit(["switch", "--no-guess", name], repositoryRoot); return getGitStatus(repositoryRoot); }
export async function stageFiles(repositoryRoot: string, paths: string[]) { if (!paths.length) throw new GitValidationError("invalid_paths", "Select at least one file."); const safe = await Promise.all(paths.map((value) => validateRepositoryPath(repositoryRoot, value))); await runGit(["add", "--", ...safe], repositoryRoot); return getGitStatus(repositoryRoot); }
export async function unstageFiles(repositoryRoot: string, paths: string[]) { if (!paths.length) throw new GitValidationError("invalid_paths", "Select at least one file."); const safe = await Promise.all(paths.map((value) => validateRepositoryPath(repositoryRoot, value))); await runGit(["restore", "--staged", "--", ...safe], repositoryRoot); return getGitStatus(repositoryRoot); }
export async function createCommit(repositoryRoot: string, message: string) { if (typeof message !== "string" || !message.trim() || message.length > 10_000) throw new GitValidationError("invalid_message", "Commit message must not be empty."); const status = await getGitStatus(repositoryRoot); if (!status.stagedFiles.length && !status.conflictedFiles.length) throw new GitError("nothing_to_commit", "Nothing is staged for commit.", 409); await runGit(["commit", "-m", message], repositoryRoot); return commitDetails(repositoryRoot); }
export async function pullRepository(repositoryRoot: string) { const status = await getGitStatus(repositoryRoot); ensureClean(status, "Pull requires a clean working tree so local changes cannot be overwritten."); if (!status.upstream) throw new GitError("no_upstream", "No upstream branch is configured.", 409); await runGit(["pull", "--no-edit"], repositoryRoot); return getGitStatus(repositoryRoot); }
export async function pushRepository(repositoryRoot: string) { const status = await getGitStatus(repositoryRoot); if (status.detached) throw new GitError("detached_head", "Push is unavailable from detached HEAD.", 409); if (!status.upstream) throw new GitError("no_upstream", "No upstream branch is configured.", 409); await runGit(["push"], repositoryRoot); return getGitStatus(repositoryRoot); }
