import { NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { validateEnvironmentInput } from "@/lib/deployments/config";
import { assertPortScopeAvailable, validateEnvironmentTarget } from "@/lib/deployments/target";
import { deploymentError, deploymentIdentity, forbidden, invalid, notAuthenticated } from "@/lib/deployments/api";
export const runtime = "nodejs"; export const dynamic = "force-dynamic";
const serverProjection = { select: { id: true, name: true, status: true, dockerAvailable: true, dockerVersion: true, hostname: true, port: true } } as const;
async function owned(projectId: string, environmentId: string) { const identity = await deploymentIdentity(); if (!identity) return { response: notAuthenticated() }; const environment = await prisma.deploymentEnvironment.findFirst({ where: { id: environmentId, projectId, project: { userId: identity.userId } } }); if (!environment) return { response: forbidden() }; return { environment }; }
export async function GET(_request: Request, context: { params: Promise<{ id: string; environmentId: string }> }) { try { const { id, environmentId } = await context.params; const access = await owned(id, environmentId); if (access.response) return access.response; return NextResponse.json({ ...access.environment, server: access.environment.serverId ? await prisma.server.findFirst({ where: { id: access.environment.serverId, userId: (await deploymentIdentity())?.userId }, ...serverProjection }) : null }); } catch (error) { return deploymentError(error); } }
export async function PATCH(request: Request, context: { params: Promise<{ id: string; environmentId: string }> }) { try { const { id, environmentId } = await context.params; const access = await owned(id, environmentId); if (access.response) return access.response; const identity = await deploymentIdentity(); const body = await request.json().catch(() => null) as Record<string, unknown> | null; if (!body) return invalid("Request body must be valid JSON.");
    let config; try { config = validateEnvironmentInput({ ...access.environment, ...body }); } catch (error) { return invalid(error instanceof Error ? error.message : "Environment configuration is invalid."); }
    // Changing an environment's target is only allowed while nothing has been deployed through it: an
    // existing container lives on whichever host the original target named.
    const changingTarget = body.target !== undefined && body.target !== access.environment.target;
    if (changingTarget) { const active = await prisma.deployment.count({ where: { environmentId, status: { in: ["running", "unhealthy", "starting", "building", "pending"] } } }); if (active) return NextResponse.json({ code: "environment_active", message: "Stop this environment's deployments before changing its deployment target." }, { status: 409 }); }
    let target; try { target = await validateEnvironmentTarget(identity?.userId ?? "", { ...access.environment, ...body }); } catch (error) { return invalid(error instanceof Error ? error.message : "Deployment target is invalid."); }
    if (await assertPortScopeAvailable(target.portScopeKey, config.hostPort, environmentId)) return NextResponse.json({ code: "port_in_use", message: "Host port is already assigned to another environment on this target." }, { status: 409 });
    return NextResponse.json(await prisma.deploymentEnvironment.update({ where: { id: environmentId }, data: { ...config, target: target.target, serverId: target.serverId, portScopeKey: target.portScopeKey } })); } catch (error) { return deploymentError(error); } }
export async function DELETE(_request: Request, context: { params: Promise<{ id: string; environmentId: string }> }) { try { const { id, environmentId } = await context.params; const access = await owned(id, environmentId); if (access.response) return access.response; const active = await prisma.deployment.count({ where: { environmentId, status: { in: ["running", "starting", "building"] } } }); if (active) return NextResponse.json({ code: "environment_active", message: "Stop active deployments before deleting an environment." }, { status: 409 }); await prisma.deploymentEnvironment.delete({ where: { id: environmentId } }); return NextResponse.json({ ok: true }); } catch (error) { return deploymentError(error); } }
