import { NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { validateEnvironmentInput } from "@/lib/deployments/config";
import { deploymentError, deploymentIdentity, forbidden, invalid, notAuthenticated } from "@/lib/deployments/api";
export const runtime = "nodejs"; export const dynamic = "force-dynamic";
async function owned(projectId: string, environmentId: string) { const identity = await deploymentIdentity(); if (!identity) return { response: notAuthenticated() }; const environment = await prisma.deploymentEnvironment.findFirst({ where: { id: environmentId, projectId, project: { userId: identity.userId } } }); if (!environment) return { response: forbidden() }; return { environment }; }
export async function GET(_request: Request, context: { params: Promise<{ id: string; environmentId: string }> }) { try { const { id, environmentId } = await context.params; const access = await owned(id, environmentId); if (access.response) return access.response; return NextResponse.json(access.environment); } catch (error) { return deploymentError(error); } }
export async function PATCH(request: Request, context: { params: Promise<{ id: string; environmentId: string }> }) { try { const { id, environmentId } = await context.params; const access = await owned(id, environmentId); if (access.response) return access.response; const body = await request.json().catch(() => null) as Record<string, unknown> | null; if (!body) return invalid("Request body must be valid JSON."); let config; try { config = validateEnvironmentInput({ ...access.environment, ...body }); } catch (error) { return invalid(error instanceof Error ? error.message : "Environment configuration is invalid."); } const port = await prisma.deploymentEnvironment.findFirst({ where: { hostPort: config.hostPort, id: { not: environmentId } } }); if (port) return NextResponse.json({ code: "port_in_use", message: "Host port is already assigned to another environment." }, { status: 409 }); return NextResponse.json(await prisma.deploymentEnvironment.update({ where: { id: environmentId }, data: config })); } catch (error) { return deploymentError(error); } }
export async function DELETE(_request: Request, context: { params: Promise<{ id: string; environmentId: string }> }) { try { const { id, environmentId } = await context.params; const access = await owned(id, environmentId); if (access.response) return access.response; const active = await prisma.deployment.count({ where: { environmentId, status: { in: ["running", "starting", "building"] } } }); if (active) return NextResponse.json({ code: "environment_active", message: "Stop active deployments before deleting an environment." }, { status: 409 }); await prisma.deploymentEnvironment.delete({ where: { id: environmentId } }); return NextResponse.json({ ok: true }); } catch (error) { return deploymentError(error); } }
