import net from "node:net";
import { deploymentDockerTimeoutMs, DockerError, runDockerCommand } from "../docker/client.ts";

export class DeploymentDockerError extends Error { code: string; status: number; constructor(code: string, message: string, status = 503) { super(message); this.code = code; this.status = status; } }
async function docker(args: string[], maxBuffer = 1024 * 1024, onOutput?: (chunk: string) => void, operation = "Docker operation") { try { return await runDockerCommand(args, maxBuffer, deploymentDockerTimeoutMs(), onOutput); } catch (error) { if (error instanceof DockerError) { const message = error.code === "timeout" ? `${operation} timed out after ${deploymentDockerTimeoutMs()} ms.` : error.message; throw new DeploymentDockerError(`docker_${error.code}`, message, error.status); } throw new DeploymentDockerError("docker_failed", `${operation} failed.`, 409); } }
export function imageTag(projectSlug: string, deploymentId: string) { return `developer-os/${projectSlug}:deployment-${deploymentId}`; }
export function containerName(projectSlug: string, environmentSlug: string, deploymentId: string) { return `developer-os-${projectSlug}-${environmentSlug}-${deploymentId.slice(0, 12)}`.replace(/[^a-zA-Z0-9_.-]/g, "-").slice(0, 120); }
export async function buildImage(repositoryRoot: string, dockerfilePath: string, tag: string, onOutput?: (chunk: string) => void) { const result = await docker(["build", "-f", dockerfilePath, "-t", tag, repositoryRoot], 4 * 1024 * 1024, onOutput, "Docker build"); return `${result.stdout}${result.stderr}`; }
export async function imageExists(tag: string) { try { await docker(["image", "inspect", tag], 64 * 1024); return true; } catch { return false; } }
export async function portAvailable(port: number) { return new Promise<boolean>((resolve) => { const server = net.createServer(); server.once("error", () => resolve(false)); server.listen(port, "127.0.0.1", () => server.close(() => resolve(true))); }); }
export async function startContainer(options: { tag: string; name: string; hostPort: number; containerPort: number; cpuLimit: string; memoryLimit: string; }) { const result = await docker(["run", "--detach", "--name", options.name, "--publish", `${options.hostPort}:${options.containerPort}`, "--cpus", options.cpuLimit, "--memory", options.memoryLimit, "--pids-limit", "256", "--restart", "unless-stopped", options.tag], 256 * 1024, undefined, "Container startup"); return result.stdout.trim().split("\n").pop() || ""; }
export async function stopOwnedContainer(containerId: string) { await docker(["stop", "--time", "10", containerId], 128 * 1024).catch(() => undefined); await docker(["rm", containerId], 128 * 1024).catch(() => undefined); }
export async function containerExists(containerId: string) { try { await docker(["inspect", containerId], 128 * 1024); return true; } catch { return false; } }
export async function healthCheck(port: number, path: string, timeoutMs: number, retries: number) { const deadline = Date.now() + deploymentDockerTimeoutMs(); for (let attempt = 0; attempt < retries && Date.now() < deadline; attempt += 1) { const remaining = Math.max(1, Math.min(timeoutMs, deadline - Date.now())); const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), remaining); try { const response = await fetch(`http://127.0.0.1:${port}${path}`, { signal: controller.signal }); if (response.ok) return { healthy: true, message: `HTTP ${response.status}` }; } catch { /* retry */ } finally { clearTimeout(timer); } const pause = Math.min(1000, remaining, Math.max(1, deadline - Date.now())); if (pause > 0) await new Promise((resolve) => setTimeout(resolve, pause)); } return { healthy: false, message: Date.now() >= deadline ? `Health check timed out after ${deploymentDockerTimeoutMs()} ms.` : "Health check did not succeed." }; }
