"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { GitBranch, GitCommit, GitDiff, GitStatus } from "@/lib/git/types";

const formatDate = (value: string) => { const date = new Date(value); return Number.isNaN(date.valueOf()) ? value : date.toLocaleString(); };
function bytesPath(root: string) { return root.split("/").pop() || root; }

export default function GitWorkspace() {
  const [repository, setRepository] = useState(".");
  const [repositoryInput, setRepositoryInput] = useState(".");
  const [status, setStatus] = useState<GitStatus | null>(null);
  const [branches, setBranches] = useState<GitBranch[]>([]);
  const [commits, setCommits] = useState<GitCommit[]>([]);
  const [diff, setDiff] = useState<GitDiff | null>(null);
  const [stagedDiff, setStagedDiff] = useState(false);
  const [selected, setSelected] = useState<string[]>([]);
  const [message, setMessage] = useState("");
  const [newBranch, setNewBranch] = useState("");
  const [state, setState] = useState<"loading" | "ready" | "error">("loading");
  const [notice, setNotice] = useState("");
  const [error, setError] = useState("");
  const query = useMemo(() => `?repository=${encodeURIComponent(repository)}`, [repository]);
  const request = useCallback(async (url: string, init?: RequestInit) => { const response = await fetch(url, { ...init, cache: "no-store", headers: { "Content-Type": "application/json", ...(init?.headers || {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.message || "Git request failed."); return body; }, []);
  const load = useCallback(async (showLoading = false) => { if (showLoading) setState("loading"); try { const [nextStatus, nextBranches, nextCommits, nextDiff] = await Promise.all([request(`/api/git/status${query}`), request(`/api/git/branches${query}`), request(`/api/git/log${query}&limit=50`), request(`/api/git/diff${query}&staged=${stagedDiff}`)]); setStatus(nextStatus); setBranches(nextBranches); setCommits(nextCommits); setDiff(nextDiff); setState("ready"); setError(""); } catch (reason) { setState("error"); setError(reason instanceof Error ? reason.message : "Git workspace unavailable."); } }, [query, request, stagedDiff]);
  useEffect(() => { const initial = window.setTimeout(() => void load(true), 0); return () => window.clearTimeout(initial); }, [load]);
  useEffect(() => { const interval = window.setInterval(() => void load(), 4000); return () => window.clearInterval(interval); }, [load]);
  const mutate = async (url: string, body: Record<string, unknown>, success: string) => { try { await request(`${url}${query}`, { method: "POST", body: JSON.stringify(body) }); setNotice(success); setSelected([]); setMessage(""); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Git operation failed."); } };
  const allFiles = [...(status?.stagedFiles || []), ...(status?.unstagedFiles || []), ...(status?.untrackedFiles || [])].filter((item, index, values) => values.findIndex((candidate) => candidate.path === item.path) === index);
  const selectedUnstaged = selected.filter((path) => status?.unstagedFiles.some((item) => item.path === path) || status?.untrackedFiles.some((item) => item.path === path));
  const selectedStaged = selected.filter((path) => status?.stagedFiles.some((item) => item.path === path));
  const requireConfirm = (text: string) => window.confirm(text);
  return <div className="git-workspace"><div className="page-header"><div><h1>Git</h1><p>Inspect and manage a validated local repository.</p></div><div className="git-connection"><span className={`status-dot status-${state === "ready" ? "green" : state === "error" ? "yellow" : "blue"}`} />{state === "ready" ? "Ready" : state === "loading" ? "Loading" : "Error"}</div></div><form className="git-repository-bar" onSubmit={(event) => { event.preventDefault(); setRepository(repositoryInput.trim() || "."); }}><label>Repository relative to GIT_WORKSPACE_ROOT<input value={repositoryInput} onChange={(event) => setRepositoryInput(event.target.value)} placeholder="." /></label><button className="secondary-button" type="submit">Open</button><button className="secondary-button" type="button" onClick={() => void load(true)}>Refresh</button></form>{error && <div className="git-banner" role="alert"><strong>Git operation failed</strong><span>{error}</span><button className="text-button" onClick={() => void load(true)}>Retry</button></div>}{notice && <div className="git-success" role="status">{notice}</div>}
    <section className="git-section"><div className="git-section-header"><h2>Repository</h2>{status && <span>{bytesPath(status.repositoryRoot)}{status.branch ? ` · ${status.branch}` : " · detached HEAD"}</span>}</div>{status && <div className="git-summary"><span>{status.clean ? "Clean working tree" : `${allFiles.length} changed file${allFiles.length === 1 ? "" : "s"}`}</span><span>{status.upstream || "No upstream"}</span><span>{status.ahead} ahead · {status.behind} behind</span>{status.remotes.map((remote) => <span key={remote.name}>{remote.name}: {remote.host}/{remote.repository}</span>)}</div>}</section>
    <section className="git-section"><div className="git-section-header"><h2>Changes</h2><div className="git-actions"><button className="secondary-button" disabled={!selectedUnstaged.length} onClick={() => void mutate("/api/git/stage", { paths: selectedUnstaged }, "Files staged.")}>Stage</button><button className="secondary-button" disabled={!selectedStaged.length} onClick={() => void mutate("/api/git/unstage", { paths: selectedStaged }, "Files unstaged.")}>Unstage</button></div></div><div className="git-file-list">{allFiles.length ? allFiles.map((item) => <label className="git-file-row" key={item.path}><input type="checkbox" checked={selected.includes(item.path)} onChange={(event) => setSelected((current) => event.target.checked ? [...current, item.path] : current.filter((path) => path !== item.path))} /><code>{item.status}</code><span>{item.path}</span>{item.originalPath && <small>from {item.originalPath}</small>}</label>) : <div className="git-empty">Working tree is clean.</div>}</div></section>
    <section className="git-section"><div className="git-section-header"><h2>Diff</h2><label className="git-toggle"><input type="checkbox" checked={stagedDiff} onChange={(event) => setStagedDiff(event.target.checked)} /> Staged</label></div><pre className="git-diff">{diff?.text || "No changes to display."}{diff?.truncated && "\n\n[Diff truncated]"}</pre></section>
    <div className="git-two-column"><section className="git-section"><div className="git-section-header"><h2>Commit</h2></div><form className="git-commit-form" onSubmit={(event) => { event.preventDefault(); void mutate("/api/git/commit", { message }, "Commit created."); }}><textarea value={message} onChange={(event) => setMessage(event.target.value)} placeholder="Commit message" rows={3} /><button className="primary-button" disabled={!status?.stagedFiles.length || !message.trim()}>Commit staged changes</button></form></section><section className="git-section"><div className="git-section-header"><h2>Actions</h2></div><div className="git-action-stack"><button className="secondary-button" disabled={!status?.upstream || status?.detached} onClick={() => requireConfirm("Pull from the configured upstream? Local changes must be clean.") && void mutate("/api/git/pull", {}, "Pull completed.")}>Pull</button><button className="secondary-button" disabled={!status?.upstream || status?.detached} onClick={() => requireConfirm("Push the current branch to its configured upstream?") && void mutate("/api/git/push", {}, "Push completed.")}>Push</button></div></section></div>
    <div className="git-two-column"><section className="git-section"><div className="git-section-header"><h2>Branches</h2></div><form className="git-inline-form" onSubmit={(event) => { event.preventDefault(); void mutate("/api/git/branch", { name: newBranch }, "Branch created."); setNewBranch(""); }}><input value={newBranch} onChange={(event) => setNewBranch(event.target.value)} placeholder="new branch name" /><button className="secondary-button">Create</button></form><div className="git-branch-list">{branches.map((branch) => <div className={`git-branch-row ${branch.current ? "current" : ""}`} key={`${branch.remote ? "remote" : "local"}-${branch.name}`}><span>{branch.current ? "●" : "○"}</span><code>{branch.name}</code>{!branch.remote && !branch.current && <button className="text-button" onClick={() => requireConfirm("Checkout this branch? The working tree must be clean.") && void mutate("/api/git/checkout", { name: branch.name }, "Branch checked out.")}>Checkout</button>}</div>)}</div></section><section className="git-section"><div className="git-section-header"><h2>History</h2></div><div className="git-history">{commits.length ? commits.map((commit) => <article key={commit.hash}><code>{commit.shortHash}</code><strong>{commit.subject}</strong><span>{commit.author} · {formatDate(commit.timestamp)}</span></article>) : <div className="git-empty">No commits found.</div>}</div></section></div>
  </div>;
}
