"use client";

import { readApiJson } from "@/lib/api/client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";

type Project = { id: string; name: string; description: string | null; status: "active" | "paused" | "archived"; githubOwner: string | null; githubRepo: string | null };
type Github = { repository: { name: string; owner: string; description: string | null; visibility: string; stars: number; forks: number; language: string | null; updatedAt: string; url: string; defaultBranch: string; openIssues: number }; languages: { name: string; percentage: number }[] };
type Container = { id: string; name: string; image: string; status: string; state: string; ports: string; created: string };
type Association = { containerId: string; container: Container | null };
type ErrorState = { code?: string; message?: string };
const formatDate = (value: string) => value ? new Date(value).toLocaleDateString() : "-";

export default function ProjectWorkspaceDetail({ id }: { id: string }) {
  const [project, setProject] = useState<Project | null>(null);
  const [github, setGithub] = useState<Github | null>(null);
  const [docker, setDocker] = useState<Association[]>([]);
  const [tab, setTab] = useState("Overview");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<ErrorState | null>(null);
  const [formOpen, setFormOpen] = useState(false);
  const [deleteOpen, setDeleteOpen] = useState(false);
  const [form, setForm] = useState({ name: "", description: "", status: "active", owner: "", repo: "" });
  const router = useRouter();

  const load = () => { Promise.all([fetch(`/api/projects/${id}`, { cache: "no-store" }), fetch(`/api/projects/${id}/docker`, { cache: "no-store" })]).then(async ([projectResponse, dockerResponse]) => { const [projectResult, dockerResult] = await Promise.all([readApiJson<{ project: Project; github: Github }>(projectResponse), readApiJson<{ items?: Association[] }>(dockerResponse)]); if (!projectResult.ok) throw Object.assign(new Error(projectResult.error.message), projectResult.error); if (!dockerResult.ok) throw Object.assign(new Error(dockerResult.error.message), dockerResult.error); const projectBody = projectResult.data; const dockerBody = dockerResult.data; setProject(projectBody.project); setGithub(projectBody.github); setDocker(dockerBody.items || []); setForm({ name: projectBody.project.name, description: projectBody.project.description || "", status: projectBody.project.status, owner: projectBody.project.githubOwner || "", repo: projectBody.project.githubRepo || "" }); setLoading(false); }).catch((reason: ErrorState) => { setError(reason); setLoading(false); }); };
  // load intentionally owns both project and Docker requests for this detail screen.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { load(); }, [id]);
  const save = async (event: React.FormEvent) => { event.preventDefault(); const response = await fetch(`/api/projects/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.name, description: form.description, status: form.status, githubOwner: form.owner || null, githubRepo: form.repo || null }) }); const result = await readApiJson<{ project: Project }>(response); if (!result.ok) { setError(result.error); return; } setProject(result.data.project); setFormOpen(false); load(); };
  const removeProject = async () => { const response = await fetch(`/api/projects/${id}`, { method: "DELETE" }); const result = await readApiJson<unknown>(response); if (result.ok) router.push("/#projects"); else setError(result.error); };
  if (loading) return <div><div className="panel state-block" role="status"><strong>Loading project</strong><span>Reading project workspace data.</span></div></div>;
  if (error || !project) return <div><div className="github-state github-error" role="alert"><strong>Project unavailable</strong><span>{error?.message || "Project not found."}</span><Link className="text-button" href="/#projects">Back to projects</Link></div></div>;
  const tabs = ["Overview", "GitHub", "Docker", "Activity"];
  return <div className="project-detail-page"><Link className="back-link" href="/#projects">← Back to projects</Link><div className="page-header"><div><div className="repository-kicker">Project workspace</div><h1>{project.name}</h1><p>{project.description || "No description provided."}</p></div><div className="header-actions"><button className="secondary-button" onClick={() => setFormOpen(true)}>Edit project</button><button className="secondary-button danger-button" onClick={() => setDeleteOpen(true)}>Delete project</button></div></div><div className="project-meta"><span className={`status status-${project.status === "active" ? "green" : project.status === "paused" ? "yellow" : "blue"}`}><span className="status-dot" />{project.status}</span>{project.githubOwner && project.githubRepo ? <Link href={`/github/repositories/${encodeURIComponent(project.githubOwner)}/${encodeURIComponent(project.githubRepo)}`}>{project.githubOwner}/{project.githubRepo}</Link> : <span>No GitHub repository connected.</span>}</div><div className="tabs" role="tablist">{tabs.map((item) => <button role="tab" aria-selected={tab === item} className={tab === item ? "tab active" : "tab"} onClick={() => setTab(item)} key={item}>{item}</button>)}</div>{tab === "Overview" && <Overview project={project} github={github} docker={docker} />}{tab === "GitHub" && <ProjectGithub project={project} github={github} />}{tab === "Docker" && <ProjectDocker id={id} items={docker} reload={load} />}{tab === "Activity" && <div className="panel state-block"><strong>{github ? "Project activity is available through GitHub" : "No recent activity"}</strong><span>{github ? "Open the GitHub tab to review repository commits, pull requests, and issues." : "Connect a GitHub repository to see project activity."}</span></div>}{formOpen && <EditProject form={form} setForm={setForm} save={save} close={() => setFormOpen(false)} />}{deleteOpen && <div className="modal-backdrop" role="presentation"><section className="project-modal confirm-modal" role="dialog" aria-modal="true" aria-labelledby="delete-title"><h2 id="delete-title">Delete {project.name}?</h2><p>Deleting this project only removes it from Developer OS. It does not delete the GitHub repository or Docker containers.</p><div className="form-actions"><button className="secondary-button" onClick={() => setDeleteOpen(false)}>Cancel</button><button className="primary-button danger-fill" onClick={removeProject}>Delete project</button></div></section></div>}</div>;
}

function Overview({ project, github, docker }: { project: Project; github: Github | null; docker: Association[] }) { return <div className="project-overview"><section className="panel"><div className="panel-header"><h2>GitHub repository</h2></div>{github ? <div className="project-repository"><Link className="repo-link" href={`/github/repositories/${encodeURIComponent(github.repository.owner)}/${encodeURIComponent(github.repository.name)}`}><strong>{github.repository.owner}/{github.repository.name}</strong></Link><span>{github.repository.description || "No description"}</span><div className="project-repo-meta"><span>{github.repository.visibility}</span><span>{github.repository.stars} stars</span><span>{github.repository.forks} forks</span><span>{github.repository.language || "Language not specified"}</span></div></div> : <div className="state-block"><strong>No GitHub repository connected.</strong><span>Edit this project to connect an accessible repository.</span></div>}</section><section className="panel"><div className="panel-header"><h2>Docker containers</h2></div>{docker.length ? <ul className="github-list">{docker.map((item) => <li key={item.containerId}><div><strong>{item.container?.name || "Unavailable container"}</strong><span>{item.container ? `${item.container.image} · ${item.container.state}` : "This container is no longer available."}</span></div></li>)}</ul> : <div className="state-block"><strong>No Docker containers connected.</strong><span>Connect containers from the Docker tab.</span></div>}</section><section className="panel project-details-panel"><div className="panel-header"><h2>Project metadata</h2></div><dl className="detail-list"><div><dt>Status</dt><dd>{project.status}</dd></div><div><dt>GitHub</dt><dd>{project.githubOwner && project.githubRepo ? `${project.githubOwner}/${project.githubRepo}` : "-"}</dd></div></dl></section></div>; }
function ProjectGithub({ project, github }: { project: Project; github: Github | null }) { return github ? <div className="project-overview"><section className="panel"><div className="panel-header"><h2>{github.repository.name}</h2><Link className="text-button" href={`/github/repositories/${encodeURIComponent(github.repository.owner)}/${encodeURIComponent(github.repository.name)}`}>Open repository</Link></div><div className="project-repo-meta project-repo-meta-large"><span>{github.repository.visibility}</span><span>{github.repository.stars} stars</span><span>{github.repository.forks} forks</span><span>{github.repository.openIssues} open issues</span><span>Updated {formatDate(github.repository.updatedAt)}</span></div></section><section className="panel"><div className="panel-header"><h2>Languages</h2></div>{github.languages.length ? github.languages.map((language) => <div className="language-row" key={language.name}><div><span>{language.name}</span><strong>{language.percentage}%</strong></div><div className="meter"><span className="meter-fill blue" style={{ width: `${language.percentage}%` }} /></div></div>) : <div className="state-block"><span>No language data available.</span></div>}</section></div> : <div className="panel state-block"><strong>No GitHub repository connected.</strong><span>Edit {project.name} to connect an accessible repository.</span></div>; }
function ProjectDocker({ id, items, reload }: { id: string; items: Association[]; reload: () => void }) { const [available, setAvailable] = useState<Container[]>([]); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(false); const loadAvailable = () => { setOpen(true); setLoading(true); fetch("/api/docker/containers", { cache: "no-store" }).then(async (response) => { const result = await readApiJson<{ items?: Container[] }>(response); if (result.ok) setAvailable(result.data.items || []); }).finally(() => setLoading(false)); }; const connect = async (containerId: string) => { await fetch(`/api/projects/${id}/docker`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ containerId }) }); setOpen(false); reload(); }; const remove = async (containerId: string) => { await fetch(`/api/projects/${id}/docker/${containerId}`, { method: "DELETE" }); reload(); }; return <section className="panel"><div className="panel-header"><h2>Connected containers</h2><button className="secondary-button" onClick={loadAvailable}>Connect container</button></div>{items.length ? <div className="table-wrap"><table><thead><tr><th>Name</th><th>Image</th><th>State</th><th>Ports</th><th>Action</th></tr></thead><tbody>{items.map((item) => <tr key={item.containerId}><td className="strong-cell">{item.container?.name || "Unavailable"}</td><td className="mono-cell">{item.container?.image || "-"}</td><td>{item.container?.state || "Unavailable"}</td><td className="mono-cell">{item.container?.ports || "-"}</td><td><button className="text-button" onClick={() => remove(item.containerId)}>Remove</button></td></tr>)}</tbody></table></div> : <div className="state-block"><strong>No Docker containers connected.</strong><span>Choose an existing local container to link it to this project.</span><button className="text-button" onClick={loadAvailable}>Connect container</button></div>}{open && <div className="modal-backdrop" role="presentation"><section className="project-modal" role="dialog" aria-modal="true" aria-labelledby="container-title"><div className="panel-header"><h2 id="container-title">Connect Docker container</h2><button className="icon-button" onClick={() => setOpen(false)} aria-label="Close container dialog">×</button></div>{loading ? <div className="state-block"><strong>Loading containers</strong></div> : available.length ? <div className="container-picker">{available.map((container) => <button className="container-option" key={container.id} onClick={() => connect(container.id)}><strong>{container.name}</strong><span>{container.image} · {container.state}</span></button>)}</div> : <div className="state-block"><strong>No containers available</strong><span>Docker returned an empty container list.</span></div>}</section></div>}</section>; }
function EditProject({ form, setForm, save, close }: { form: { name: string; description: string; status: string; owner: string; repo: string }; setForm: (form: { name: string; description: string; status: string; owner: string; repo: string }) => void; save: (event: React.FormEvent) => void; close: () => void }) { return <div className="modal-backdrop" role="presentation"><section className="project-modal" role="dialog" aria-modal="true" aria-labelledby="edit-project-title"><div className="panel-header"><h2 id="edit-project-title">Edit project</h2><button className="icon-button" onClick={close} aria-label="Close edit project dialog">×</button></div><form className="project-form" onSubmit={save}><label>Name<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>Description<textarea rows={3} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label><label>Status<select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })}><option value="active">Active</option><option value="paused">Paused</option><option value="archived">Archived</option></select></label><label>GitHub owner<input value={form.owner} onChange={(event) => setForm({ ...form, owner: event.target.value })} placeholder="Optional" /></label><label>GitHub repository<input value={form.repo} onChange={(event) => setForm({ ...form, repo: event.target.value })} placeholder="Optional" /></label><div className="form-actions"><button type="button" className="secondary-button" onClick={close}>Cancel</button><button className="primary-button" type="submit">Save changes</button></div></form></section></div>; }
